In [5]:
#importing libraries

import pandas as pd
import datetime
from datetime import date, timedelta
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import warnings
warnings.filterwarnings("ignore")

#Penalty

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Penalty')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[0,1,2,7,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date of Fine']= df['Date of Fine'].str.replace('-', '/')
df['Date of Fine'] = pd.to_datetime(df['Date of Fine'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
df_5week = df[(df['Date of Fine'] >= pd.to_datetime(previous_monday_week)) & (df['Date of Fine'] < pd.to_datetime(previous_monday))]
df_5week['Date of Fine']=df_5week['Date of Fine'].astype(str)
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Penalty')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#B2B

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('B2B')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[1,3,12,4]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date']= df['Date'].str.replace('-', '/')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
df_5week['Date']=df_5week['Date'].astype(str)
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('B2B')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')


#Recovery

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Recovery')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[0,2,5,6]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date']= df['Date'].str.replace('-', '/')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
df_5week['Date']=df_5week['Date'].astype(str)
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Recovery')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#Adjustments

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Adjustments')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[0,1,3,4,5,7]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date']= df['Date'].str.replace('-', '/')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
df_5week['Date']=df_5week['Date'].astype(str)
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Adjustments')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#RTO

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('RTO')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[0,1,2,6,4]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date of Fine']= df['Date of Fine'].str.replace('-', '/')
df['Date of Fine'] = pd.to_datetime(df['Date of Fine'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
df_5week = df[(df['Date of Fine'] >= pd.to_datetime(previous_monday_week)) & (df['Date of Fine'] < pd.to_datetime(previous_monday))]
df_5week['Date of Fine']=df_5week['Date of Fine'].astype(str)
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('RTO')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#Driver hisaab

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Driver Hisaab')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[1,2,3,4,5]]
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Driver Hisaab')
ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')

#Amount paid

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Amount Paid')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[1,2,5]]
df.columns
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date']= df['Date'].str.replace('-', '/')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
df_5week['Date']=df_5week['Date'].astype(str)
df_5week.dtypes
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Amount Paid')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#New sms data

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('New SMS Data')
data = ws.get_all_values()
headers = data.pop(1)
dfm = pd.DataFrame(data,columns=headers)
# dfm.iloc[0:-1,[2,3,4,26,31,32]]
# dfm.loc[:,['Contact No','Name','ETM','Total Earnings(Sum(Q:S)-T)','Pending Joining Fee','Total Outstanding as of 08 May']]
a=dfm.loc[:,['Contact No','Name','ETM','Total Earnings(Sum(Q:S)-T)','Pending Joining Fee']]
b=dfm.iloc[0:-1,[32]]
df= pd.concat([a, b], axis=1, join="inner")
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('New SMS Data')
ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')

#driver leaving

# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('atmanirbhar-test-f9b83b6f0672.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Car Recovery Process')
# ws= sheet.worksheet('Driver Leaving Form')
# data = ws.get_all_values()
# headers = data.pop(0)
# dfm = pd.DataFrame(data,columns=headers)
# df=dfm.iloc[0:-1,[0,1,2,5]]
# today = datetime.date.today()
# previous_monday = today - datetime.timedelta(days=today.weekday())
# previous_monday_week= previous_monday - datetime.timedelta(days=35)
# df['Timestamp']= df['Timestamp'].str.replace('-', '/')
# df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
# df_5week = df[(df['Timestamp'] >= pd.to_datetime(previous_monday_week)) & (df['Timestamp'] < pd.to_datetime(previous_monday))]
# df_5week['Timestamp']=df_5week['Timestamp'].astype(str)
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Driver Leaving')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#Allotment status report

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Allotment Status Report')
ws= sheet.worksheet('Allotment Status Report')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[2,16,7,3]] #Dm comparing etm with dm
allot=df[df.ID.str.startswith('ETM')]
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Allotment Status Report')
ws.update([allot.columns.values.tolist()] + allot.values.tolist(),value_input_option='USER_ENTERED')

#uber

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Uber')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Week start Date']= df['Week start Date'].str.replace('-', '/')
df['Week start Date'] = pd.to_datetime(df['Week start Date'], errors='coerce')#,format='%m/%d/%Y')#27/12/2021
df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Uber')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#cancel

# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('atmanirbhar-test-f9b83b6f0672.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Car Recovery Process')
# ws= sheet.worksheet('Recovery Queries')
# data = ws.get_all_values()
# headers = data.pop(0)
# df = pd.DataFrame(data,columns=headers)
# today = datetime.date.today()
# previous_monday = today - datetime.timedelta(days=today.weekday())
# previous_monday_week= previous_monday - datetime.timedelta(days=35)
# df['Timestamp']= df['Timestamp'].str.replace('-', '/')
# df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')#,format='%m/%d/%Y %H:%M:%S')#27/12/2021
# df_5week = df[(df['Timestamp'] >= pd.to_datetime(previous_monday_week)) & (df['Timestamp'] < pd.to_datetime(previous_monday))]
# df_5week['Timestamp']=df_5week['Timestamp'].astype(str)
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Cancel')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#vistor response

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('New Visitors Form at Korum Mall,Thane ')
ws= sheet.worksheet('Vistor Responses')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[0,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Timestamp']= df['Timestamp'].str.replace('-', '/')
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')#,format='%m/%d/%Y %H:%M:%S')#27/12/2021
df_5week = df[(df['Timestamp'] >= pd.to_datetime(previous_monday_week)) & (df['Timestamp'] < pd.to_datetime(previous_monday))]
df_5week['Timestamp']=df_5week['Timestamp'].astype(str)
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Vistor Responses')
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
ws.update(data)

#sedan new sms

# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('atmanirbhar-test-f9b83b6f0672.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Car Master Sheet')
# ws= sheet.worksheet('Sedan New SMS')
# data = ws.get_all_values()
# headers = data.pop(1)
# dfm = pd.DataFrame(data,columns=headers)
# # df=dfm.iloc[0:-1,[2,3,4,23,28,29]]
# df=dfm.loc[:,['Contact No','Name','ETM','Total Earnings\n(Sum(Q:S)-T)','Pending Joining Fee','Total Outstanding as of 02 May']]
# # df=dfm.loc[:,['Contact No','Name','ETM','Total Earnings(Sum(Q:S)-T)','Pending Joining Fee','Total Outstanding as of 01 May']]
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Sedan New SMS')
# ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')

#DM

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car No Master list ')
ws= sheet.worksheet('Current')
data = ws.get_all_values()
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('DM')
ws.update(data)

print('updated successfully')

updated successfully

In [15]:
exam= pd.DataFrame({"a" : [1,1,1,1,2,2,2,2], "b" : [2,3,1,4,5,6,7,2], "c" : [1,2,3,4,5,6,7,8]})

In [22]:
a=exam.loc[:,['a']]
b=exam.iloc[0:-1,[1,2]]

In [24]:
result = pd.concat([a, b], axis=1, join="inner")
result

   a  b  c
0  1  2  1
1  1  3  2
2  1  1  3
3  1  4  4
4  2  5  5
5  2  6  6
6  2  7  7

In [25]:
scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('New SMS Data')
data = ws.get_all_values()
headers = data.pop(1)
dfm = pd.DataFrame(data,columns=headers)
# dfm.iloc[0:-1,[2,3,4,26,31,32]]
# dfm.loc[:,['Contact No','Name','ETM','Total Earnings(Sum(Q:S)-T)','Pending Joining Fee','Total Outstanding as of 08 May']]
# a=dfm.loc[:,['Contact No','Name','ETM','Total Earnings(Sum(Q:S)-T)','Pending Joining Fee']]
# b=dfm.iloc[0:-1,[32]]
# df= pd.concat([a, b], axis=1, join="inner")
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('New SMS Data')
# ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')

,Contact No,Name,ETM,Total Earnings(Sum(Q:S)-T),Pending Joining Fee,Total Outstanding as of 08 May
0,,Week Start Date,02/05/2022,,,
1,9619772163,Mohd Hasib,ETM00118,0,0,-60
2,9561791567,Sameer S Gamare,ETM00340,"-3,159.86",0,"-3,160"
3,7021921014,Grijesh Pandey,ETM00365,"5,549.50",0,"5,550"
4,9372950747,Rajesh Wadkar,ETM00388,331.60,0,"-2,251"
...,...,...,...,...,...,...
1222,9082077055,Sushant Tare,ETM12243,"-3,507.73",0,"-3,507"
1223,9819074617,Musab Khan,ETM01685,181.85,0,59
1224,9309786979,Bhimashankara Actari,ETM09949,"-3,449.31",0,"-3,572"
1225,8454913505,Arbaz Khan,ETM00992,"11,675.75",0,"7,471"
1226,9167295623,Rashid Khan,ETM00047,"18,314.95",0,"5,766"

In [26]:
scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('New SMS Data')
data = ws.get_all_values()
headers = data.pop(1)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[0:-1,[2,3,4,26,31,32]]
df
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('New SMS Data')
# ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')

,Contact No,Name,ETM,Total Earnings(Sum(Q:S)-T),Pending Joining Fee,Total Outstanding as of 08 May
0,,Week Start Date,02/05/2022,,,
1,9619772163,Mohd Hasib,ETM00118,0,0,-60
2,9561791567,Sameer S Gamare,ETM00340,"-3,159.86",0,"-3,160"
3,7021921014,Grijesh Pandey,ETM00365,"5,549.50",0,"5,550"
4,9372950747,Rajesh Wadkar,ETM00388,331.60,0,"-2,251"
...,...,...,...,...,...,...
1222,9082077055,Sushant Tare,ETM12243,"-3,507.73",0,"-3,507"
1223,9819074617,Musab Khan,ETM01685,181.85,0,59
1224,9309786979,Bhimashankara Actari,ETM09949,"-3,449.31",0,"-3,572"
1225,8454913505,Arbaz Khan,ETM00992,"11,675.75",0,"7,471"
1226,9167295623,Rashid Khan,ETM00047,"18,314.95",0,"5,766"