In [1]:
#importing libraries

import pandas as pd
import datetime
from datetime import date, timedelta
# import gspread
import pygsheets
# from oauth2client.service_account import ServiceAccountCredentials
import warnings
warnings.filterwarnings("ignore")

#clients

clients = pygsheets.authorize(service_file='client_secret.json')

# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# client= gspread.authorize(credentials)

#Penalty

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Penalty')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,2,7,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Date of Fine']= df['Date of Fine'].str.replace('/', '-')
df['Date in Payout']= df['Date in Payout'].str.replace('/', '-')
df[['Date of Fine','Date in Payout']] = df[['Date of Fine','Date in Payout']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Date of Fine'] >= pd.to_datetime(previous_monday_week)) & (df['Date of Fine'] < pd.to_datetime(previous_monday))]
df_5week['Date of Fine']=df_5week['Date of Fine'].astype(str)
df_5week['Date in Payout']=df_5week['Date in Payout'].astype(str)
#Aatmanirbhar -3
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Penalty')
# ws.clear()
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Penalty')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Penalty')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Penalty')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
# #Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Penalty')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Penalty')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Penalty')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Penalty updated successfully")

#B2B

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('B2B')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[1,3,12,4]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Date']= df['Date'].str.replace('/', '-')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
df_5week['Date']=df_5week['Date'].astype(str)
#Aatmanirbhar -3
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('B2B')
# ws.clear()
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('B2B')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('B2B')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('B2B')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('B2B')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('B2B')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('B2B')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("B2B updated successfully")

#Recovery

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Recovery')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,2,5,6]]
today = datetime.date.today()
previous_monday_week= today - datetime.timedelta(days=56)
df['Date']= df['Date'].str.replace('-', '/')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d/%m/%Y')#27/12/2021
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(today))]
df_5week['Date']=df_5week['Date'].astype(str)
#Recovery not in Aatmanirbhar -3 
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Recovery')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Recovery')
ws.clear(start='A',end='D')
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Recovery')
ws.clear(start='A',end='D')
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Recovery')
ws.clear(start='A',end='D')
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Recovery')
ws.clear(start='A',end='D')
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Recovery')
ws.clear(start='A',end='D')
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Recovery')
ws.clear(start='A',end='D')
ws.set_dataframe(df_5week,(1,1))
print("Recovery updated successfully")

#Adjustments

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Adjustments')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,7,3]]
today = datetime.date.today()
previous_monday_week= today - datetime.timedelta(days=56)
df['Date']= df['Date'].str.replace('/', '-')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')#03/06/2022
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] <= pd.to_datetime(today))]
df_5week['Date']=df_5week['Date'].astype(str)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments') 
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Adjustment updated successfully")

#RTO

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('RTO')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,2,6,4]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Date of Fine']= df['Date of Fine'].str.replace('/', '-')
df['Date in Payout']= df['Date in Payout'].str.replace('/', '-')
df[['Date of Fine','Date in Payout']] = df[['Date of Fine','Date in Payout']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Date of Fine'] >= pd.to_datetime(previous_monday_week)) & (df['Date of Fine'] < pd.to_datetime(previous_monday))]
df_5week['Date of Fine']=df_5week['Date of Fine'].astype(str)
df_5week['Date in Payout']=df_5week['Date in Payout'].astype(str)
#Aatmanirbhar -3
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('RTO')
# ws.clear()
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('RTO')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('RTO')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('RTO')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('RTO')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('RTO')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('RTO')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Rto updated successfully")

#Driver hisaab

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Driver Hisaab')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[1,2,3,4,5]]
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('Driver Hisaab')
ws.clear()
ws.set_dataframe(df,(1,1))
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Driver Hisaab')
ws.clear()
ws.set_dataframe(df,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Driver Hisaab')
ws.clear()
ws.set_dataframe(df,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Driver Hisaab')
ws.clear()
ws.set_dataframe(df,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Driver Hisaab')
ws.clear()
ws.set_dataframe(df,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Driver Hisaab')
ws.clear()
ws.set_dataframe(df,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Driver Hisaab')
ws.clear()
ws.set_dataframe(df,(1,1))
print("Driver hisaab updated successfully")

#Amount paid

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Amount Paid')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[1,2,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Date']= df['Date'].str.replace('/', '-')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')#27/12/2021
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
df_5week['Date']=df_5week['Date'].astype(str)
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Amount Paid')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Amount Paid')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Amount Paid')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Amount Paid')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Amount Paid')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Amount Paid')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Amount paid updated successfully")

#New sms data

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('New SMS Data')
data = ws.get_all_values()
headers = data.pop(1)
dfm = pd.DataFrame(data,columns=headers)
reject_df=dfm.loc[dfm['Sum of Trips'] > '0']
df=reject_df.iloc[:,[2,3,4,26,31,32,0,1,36]]

car_no_ms_ls='11D8_6u4ywy3yNYyrnMonyti6eflqUtpMfsxgLMBXEzk'

sheet= clients.open_by_key(car_no_ms_ls)#car no master list comparison car
ws= sheet.worksheet_by_title('Current')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
car_number_matching=dfm.iloc[:,[0]]
car_number_matching.rename({'car_number':'vehicle no'},axis=1,inplace=True)
new_sms_filter_data_df=df.merge(car_number_matching,on='vehicle no',how='inner')#comparing the car no is present in car no master or not in new sms data 
new_sms_filter_data=new_sms_filter_data_df.iloc[:,[0,1,2,3,4,5,6,7,8]]
new_sms_filter_data

#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('New SMS Data')
ws.clear(start='A',end='I')
ws.set_dataframe(new_sms_filter_data,(1,1))
print("New sms data updated successfully")

#Allotment status report

# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Allotment Status Report')
# ws= sheet.worksheet('Allotment Status Report')
# data = ws.get_all_values()
# headers = data.pop(0)
# dfm = pd.DataFrame(data,columns=headers)
# df=dfm.iloc[:,[2,16,7,3]] #Dm comparing etm with dm
# allot=df[df.ID.str.startswith('ETM')]
# #Aatmanirbhar -3
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Allotment Status Report')
# ws.update([allot.columns.values.tolist()] + allot.values.tolist(),value_input_option='USER_ENTERED')
# print("Allotment status report updated successfully")

#uber

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Uber')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Week start Date']= df['Week start Date'].str.replace('/', '-')
df['Week End Date']= df['Week End Date'].str.replace('/', '-')
df[['Week start Date','Week End Date']] = df[['Week start Date','Week End Date']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
df_5week['Week End Date']=df_5week['Week End Date'].astype(str)
# not to update Uber in 26/05/2022 Aatmanirbhar -3 
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Uber updated successfully")

#vistor response

sheet= clients.open('New Visitors Form at Korum Mall,Thane ')
ws= sheet.worksheet_by_title('Vistor Responses')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Timestamp']= df['Timestamp'].str.replace('/', '-')
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce',format='%d-%m-%Y %H:%M:%S')#27/12/2021
df_5week = df[(df['Timestamp'] >= pd.to_datetime(previous_monday_week)) & (df['Timestamp'] < pd.to_datetime(previous_monday))]
df_5week['Timestamp']=df_5week['Timestamp'].astype(str)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('Vistor Responses')
ws.clear(start='A',end='B')
ws.set_dataframe(df_5week,(1,1))
print("Vistor responses updated successfully")

#DM

sheet= clients.open('Car No Master list')
ws= sheet.worksheet_by_title('Current')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('DM')
ws.clear()
ws.set_dataframe(dfm,(1,1))
print("Dm updated successfully")
print("\n")

print('All sheets updated successfully')

Penalty updated successfully
B2B updated successfully
Recovery updated successfully
Adjustment updated successfully
Rto updated successfully
Driver hisaab updated successfully
Amount paid updated successfully
New sms data updated successfully
Uber updated successfully
Vistor responses updated successfully
Dm updated successfully


All sheets updated successfully

In [3]:
# #importing libraries

# import pandas as pd
# import datetime
# from datetime import date, timedelta
# # import gspread
# import pygsheets
# # from oauth2client.service_account import ServiceAccountCredentials
# import warnings
# warnings.filterwarnings("ignore")

# #clients

# clients = pygsheets.authorize(service_file='client_secret.json')

# # scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# # credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# # client= gspread.authorize(credentials)

# #Penalty

# sheet= clients.open('Car Master Sheet')
# ws= sheet.worksheet_by_title('Penalty')
# data = ws.get_all_values()
# headers = data.pop(0)
# dfm = pd.DataFrame(data,columns=headers)
# df=dfm.loc[:,['Date of Fine','Date in Payout','ETM','Fine Amount','Penalty']]
# today = datetime.date.today()
# previous_monday = today - datetime.timedelta(days=today.weekday())
# previous_monday_week= previous_monday - datetime.timedelta(days=56)
# df['Date of Fine']= df['Date of Fine'].str.replace('/', '-')
# df['Date in Payout']= df['Date in Payout'].str.replace('/', '-')
# df[['Date of Fine','Date in Payout']] = df[['Date of Fine','Date in Payout']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
# df_5week = df[(df['Date of Fine'] >= pd.to_datetime(previous_monday_week)) & (df['Date of Fine'] < pd.to_datetime(previous_monday))]
# df_5week['Date of Fine']=df_5week['Date of Fine'].astype(str)
# df_5week['Date in Payout']=df_5week['Date in Payout'].astype(str)
# df_5week

,Date of Fine,Date in Payout,ETM,Fine Amount,Penalty
42,2022-07-01,2022-01-08,ETM06053,-800,Car Mis-use
43,2022-07-01,2022-01-08,ETM14216,-300,Other
175,2022-07-02,2022-02-07,ETM13886,-1600,Side Rear View Mirror Broken
176,2022-07-02,2022-02-07,ETM10428,-800,Side Rear View Mirror Broken
177,2022-07-02,2022-02-07,ETM14779,-2400,Car Mis-use
...,...,...,...,...,...
2082,2022-08-07,2022-08-09,ETM23577,-500,ND Fine
2083,2022-08-07,2022-08-09,ETM24061,-500,ND Fine
2092,2022-08-05,2022-08-10,ETM22473,-2000,Accident
2093,2022-08-04,2022-08-10,ETM21685,-800,Wind Shield Rear View Mirror
2094,2022-07-30,2022-08-10,ETM06766,-850,Key Lost

In [5]:
#uber

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Uber')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Week start Date']= df['Week start Date'].str.replace('/', '-')
df['Week End Date']= df['Week End Date'].str.replace('/', '-')
df[['Week start Date','Week End Date']] = df[['Week start Date','Week End Date']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
df_5week['Week End Date']=df_5week['Week End Date'].astype(str)
# not to update Uber in 26/05/2022 Aatmanirbhar -3 
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Uber updated successfully")

#vistor response

sheet= clients.open('New Visitors Form at Korum Mall,Thane ')
ws= sheet.worksheet_by_title('Vistor Responses')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Timestamp']= df['Timestamp'].str.replace('/', '-')
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce',format='%d-%m-%Y %H:%M:%S')#27/12/2021
df_5week = df[(df['Timestamp'] >= pd.to_datetime(previous_monday_week)) & (df['Timestamp'] < pd.to_datetime(previous_monday))]
df_5week['Timestamp']=df_5week['Timestamp'].astype(str)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('Vistor Responses')
ws.clear(start='A',end='B')
ws.set_dataframe(df_5week,(1,1))
print("Vistor responses updated successfully")

#DM

sheet= clients.open('Car No Master list')
ws= sheet.worksheet_by_title('Current')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('DM')
ws.clear()
ws.set_dataframe(dfm,(1,1))
print("Dm updated successfully")
print("\n")

print('All sheets updated successfully')

Uber updated successfully
Vistor responses updated successfully
Dm updated successfully


All sheets updated successfully

In [5]:
#importing libraries

import pandas as pd
import datetime
from datetime import date, timedelta
import pygsheets
import warnings
warnings.filterwarnings("ignore")

#clients

clients = pygsheets.authorize(service_file='client_secret.json')


#Adjustments

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Adjustments')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,7,3]]
today = datetime.date.today()
previous_monday_week= today - datetime.timedelta(days=56)
df['Date']= df['Date'].str.replace('/', '-')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')#03/06/2022
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] <= pd.to_datetime(today))]
df_5week['Date']=df_5week['Date'].astype(str)
df_5week
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Adjustments') 
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Adjustment updated successfully")

Adjustment updated successfully

In [4]:
#uber

sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Uber')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Week start Date']= df['Week start Date'].str.replace('/', '-')
df['Week End Date']= df['Week End Date'].str.replace('/', '-')
df[['Week start Date','Week End Date']] = df[['Week start Date','Week End Date']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
df_5week['Week End Date']=df_5week['Week End Date'].astype(str)
# not to update Uber in 26/05/2022 Aatmanirbhar -3 
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Uber updated successfully")

#vistor response

sheet= clients.open('New Visitors Form at Korum Mall,Thane ')
ws= sheet.worksheet_by_title('Vistor Responses')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=56)
df['Timestamp']= df['Timestamp'].str.replace('/', '-')
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce',format='%d-%m-%Y %H:%M:%S')#27/12/2021
df_5week = df[(df['Timestamp'] >= pd.to_datetime(previous_monday_week)) & (df['Timestamp'] < pd.to_datetime(previous_monday))]
df_5week['Timestamp']=df_5week['Timestamp'].astype(str)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('Vistor Responses')
ws.clear(start='A',end='B')
ws.set_dataframe(df_5week,(1,1))
print("Vistor responses updated successfully")

#DM

sheet= clients.open('Car No Master list')
ws= sheet.worksheet_by_title('Current')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('DM')
ws.clear()
ws.set_dataframe(dfm,(1,1))
print("Dm updated successfully")
print("\n")

print('All sheets updated successfully')

Uber updated successfully
Vistor responses updated successfully
Dm updated successfully


All sheets updated successfully

In [4]:
# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# client= gspread.authorize(credentials)
#importing libraries

import pandas as pd
import datetime
from datetime import date, timedelta
import gspread
import pygsheets
from oauth2client.service_account import ServiceAccountCredentials
import warnings
warnings.filterwarnings("ignore")

#clients

clients = pygsheets.authorize(service_file='client_secret.json')

In [6]:
#uber

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Uber')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Week start Date']= df['Week start Date'].str.replace('/', '-')
df['Week End Date']= df['Week End Date'].str.replace('/', '-')
df[['Week start Date','Week End Date']] = df[['Week start Date','Week End Date']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
df_5week['Week End Date']=df_5week['Week End Date'].astype(str)
# not to update Uber in 26/05/2022 Aatmanirbhar -3 
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

#Deep Hunters - Hisaab Tab
sheet= clients.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Roaring Lions - Hisaab Tab
sheet= clients.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Black Panthers - Hisaab Tab
sheet= clients.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Silent Killers - Hisaab Tab
sheet= clients.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Terrific Tigers - Hisaab Tab
sheet= clients.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
#Attrition Team - Hisaab Tab
sheet= clients.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet_by_title('Uber')
ws.clear()
ws.set_dataframe(df_5week,(1,1))
print("Uber updated successfully")

#vistor response

sheet= clients.open('New Visitors Form at Korum Mall,Thane ')
ws= sheet.worksheet_by_title('Vistor Responses')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Timestamp']= df['Timestamp'].str.replace('/', '-')
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce',format='%d-%m-%Y %H:%M:%S')#27/12/2021
df_5week = df[(df['Timestamp'] >= pd.to_datetime(previous_monday_week)) & (df['Timestamp'] < pd.to_datetime(previous_monday))]
df_5week['Timestamp']=df_5week['Timestamp'].astype(str)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('Vistor Responses')
ws.clear(start='A',end='B')
ws.set_dataframe(df_5week,(1,1))
print("Vistor responses updated successfully")

#DM

sheet= clients.open('Car No Master list')
ws= sheet.worksheet_by_title('Current')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
#Aatmanirbhar -3
sheet= clients.open('Aatmanirbhar -3')
ws= sheet.worksheet_by_title('DM')
ws.clear()
ws.set_dataframe(dfm,(1,1))
print("Dm updated successfully")
print("\n")

print('All sheets updated successfully')

Uber updated successfully
Vistor responses updated successfully
Dm updated successfully


All sheets updated successfully

In [5]:
#uber

sheet= clients.open('Car Master Sheet')
ws= sheet.worksheet_by_title('Uber')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Week start Date']= df['Week start Date'].str.replace('/', '-')
df['Week End Date']= df['Week End Date'].str.replace('/', '-')
df[['Week start Date','Week End Date']] = df[['Week start Date','Week End Date']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
df_5week['Week End Date']=df_5week['Week End Date'].astype(str)
df_5week

,Week start Date,Week End Date,ETM,Contact No,Name,Trips,Tips,Toll As Per Uber App,Toll Paid by Fast tag,Tolls,...,Incentive,Final 60:40 Uber OS,Online Hours,Earning w/o Toll,Cancellation Rate,Acceptance Rate,Sedan Earning w/o Toll,Sedan Cash,Sedan 55.%,Sedan 55.% - Sedan Cash
26300,2022-06-13,2022-06-19,ETM00340,9561791567,Sameer s Gamare,43,50,450,280,170,...,0,-2795,81.5,10934.15,9,88,0,0,0,0
26301,2022-06-13,2022-06-19,ETM00388,9372950747,Rajesh Wadkar,55,100,540,200,340,...,950,-22,66.3,12906.63,1,78,0,0,0,0
26302,2022-06-13,2022-06-19,ETM00446,9653496276,Dinesh Akhade,87,0,1100,760,340,...,1850,-3568,79.33,21719.58,2,95,0,0,0,0
26303,2022-06-13,2022-06-19,ETM00479,9930446885,Suresh Vishwakarma,71,0,1120,440,680,...,1350,873,81.3,15190.31,7,85,0,0,0,0
26304,2022-06-13,2022-06-19,ETM00554,8169165569,VINAYKUMAR YADAV,10,0,165,80,85,...,0,-744,17.27,3014.5,8,58,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33028,2022-07-11,2022-07-17,ETM13907,7977438106,Tushar Pawar,13,0,200,200,0,...,0,74,24.2,122.51,9,56,3580.28,-2758,"1,969",-789
33029,2022-07-11,2022-07-17,ETM19576,9167685068,mohd aariz javed khan -,17,25,160,160,0,...,0,-86,27.3,1051.93,6,74,2377,-1375,"1,307",-68
33030,2022-07-11,2022-07-17,ETM12342,8850720590,Nadeem Baig,36,0,815,560,255,...,0,-806,46.54,4382.62,12,84,6790.64,-6923,"3,735","-3,188"
33031,2022-07-11,2022-07-17,ETM11315,6205048787,Kush Tiwari,50,0,740,400,340,...,0,-1528,60.19,14765.81,4,88,252.92,-360,139,-221
33032,2022-07-11,2022-07-17,ETM03059,7572015535,ABHISHEK CHAUHAN,77,75,755,160,595,...,1350,2761,69.11,10611.9,0,94,4810.04,-3358,"2,646",-712

In [18]:
new_sms_filter_data=df.merge(car_number_matching,on='vehicle no',how='left')
new_sms_filter_data

,Contact No,Name,ETM,Total Earnings(Sum(Q:S)-T),Pending Joining Fee,Total Outstanding as of 11 July,Fleet,DM,vehicle no
0,9619772163,Mohd Hasib,ETM00118,0,0,-60,#N/A,#N/A,#N/A
1,8618865163,Manoj L,Etm22918,"-1,770.07",0,-615,Everest - MUM 16,#N/A,#N/A
2,9561791567,Sameer S Gamare,ETM00340,-541.58,0,0,Everest - MUM 4,Silent Killers,MH01DR3239
3,9372950747,Rajesh Wadkar,ETM00388,"-4,311.19",0,"-9,039",Everest - MUM 7,Deep Hunters,MH01DR4137
4,9653496276,Dinesh Akhade,ETM00446,"1,625.70",0,966,Everest - MUM 4,Silent Killers,MH01DR8805
...,...,...,...,...,...,...,...,...,...
1352,7506977710,Jitendra Kumar Atmaram Varma,ETM21146,"-1,585.69",0,"-6,270",Everest - MUM 5,Terrific Tigers,#N/A
1353,9137387463,Ankesh Dalvi,ETM21084,"-1,601.34",0,"-2,274",Everest - MUM 1,Black Panthers,MH01DR5116
1354,9112585891,Anand Kumar Rav,ETM20877,584.06,0,"1,648",Everest - MUM 13,Silent Killers,MH01DR4088
1355,8591715342,Meraj Ansari,ETM16904,"-4,399.55",0,"-5,399",Everest - MUM 14,Deep Hunters,MH01DR3894
1356,7783845027,Barkat Ali,ETM19064,"-2,714.57",0,"-6,604",Everest - MUM 7,Deep Hunters,MH01DR4502

# Rough work

In [3]:
#Adjustments

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Adjustments')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,7,3]]
# today = datetime.date.today()
# previous_monday = today - datetime.timedelta(days=today.weekday())
# previous_monday_week= previous_monday - datetime.timedelta(days=35)
# df['Date']= df['Date'].str.replace('/', '-')
# df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')
# df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
# df_5week['Date']=df_5week['Date'].astype(str)

today = datetime.date.today()
previous_monday_week= today - datetime.timedelta(days=42)
df['Date']= df['Date'].str.replace('/', '-')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')#03/06/2022
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(today))]
df_5week['Date']=df_5week['Date'].astype(str)

#Aatmanirbhar -3
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Adjustments')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Deep Hunters - Hisaab Tab
sheet= client.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet('Adjustments')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Roaring Lions - Hisaab Tab
sheet= client.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet('Adjustments')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Black Panthers - Hisaab Tab
sheet= client.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet('Adjustments')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Silent Killers - Hisaab Tab
sheet= client.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet('Adjustments')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Terrific Tigers - Hisaab Tab
sheet= client.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet('Adjustments')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Attrition Team - Hisaab Tab
sheet= client.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet('Adjustments')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
print("Adjustment updated successfully")

Adjustment updated successfully

In [ ]:
#Allotment status report

# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Allotment Status Report')
# ws= sheet.worksheet('Allotment Status Report')
# data = ws.get_all_values()
# headers = data.pop(0)
# dfm = pd.DataFrame(data,columns=headers)
# df=dfm.iloc[:,[2,16,7,3]] #Dm comparing etm with dm
# allot=df[df.ID.str.startswith('ETM')]
# #Aatmanirbhar -3
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Allotment Status Report')
# ws.update([allot.columns.values.tolist()] + allot.values.tolist(),value_input_option='USER_ENTERED')
# print("Allotment status report updated successfully")

In [8]:
#Adjustments

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Adjustments')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,7,3]]
# today = datetime.date.today()
# previous_monday = today - datetime.timedelta(days=today.weekday())
# previous_monday_week= previous_monday - datetime.timedelta(days=35)
# df['Date']= df['Date'].str.replace('/', '-')
# df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')
# df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
# df_5week['Date']=df_5week['Date'].astype(str)

today = datetime.date.today()
previous_monday_week= today - datetime.timedelta(days=42)
df['Date']= df['Date'].str.replace('/', '-')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')#03/06/2022
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] <= pd.to_datetime(today))]
df_5week['Date']=df_5week['Date'].astype(str)

,Date,ETM ID,Amount,Remark,Status,Type
6656,2022-04-23,ETM11317,157,Need to adjust deposit as driver left in week ...,TRUE,Deposit adjustments
6657,2022-04-23,ETM11372,489,Need to adjust deposit as driver left in week ...,TRUE,Deposit adjustments
6658,2022-04-23,ETM11595,398,Need to adjust deposit as driver left in week ...,TRUE,Deposit adjustments
6659,2022-04-23,ETM11728,1243,Need to adjust deposit as driver left in week ...,TRUE,Deposit adjustments
6660,2022-04-23,ETM12359,1561,Need to adjust deposit as driver left in week ...,TRUE,Deposit adjustments
...,...,...,...,...,...,...
10846,2022-06-03,ETM17242,40,Need to add Adjustment of Rs 40 for-TOLL Car N...,FALSE,
10847,2022-06-03,ETM20601,100,Need to add Adjustment of Rs 100 for-Puncture ...,FALSE,
10848,2022-06-03,ETM14200,300,Need to add Adjustment of Rs 300 for-Puncture ...,FALSE,
10849,2022-06-03,ETM19729,170,Need to add Adjustment of Rs 170 for-Puncture ...,FALSE,
10850,2022-06-03,ETM07674,2000,Need to add Adjustment of Rs 2000 for-carrier ...,FALSE,

In [ ]:
#Penalty

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Penalty')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,2,7,5]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date of Fine']= df['Date of Fine'].str.replace('/', '-')
df['Date in Payout']= df['Date in Payout'].str.replace('/', '-')
df[['Date of Fine','Date in Payout']] = df[['Date of Fine','Date in Payout']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Date of Fine'] >= pd.to_datetime(previous_monday_week)) & (df['Date of Fine'] < pd.to_datetime(previous_monday))]
df_5week['Date of Fine']=df_5week['Date of Fine'].astype(str)
df_5week['Date in Payout']=df_5week['Date in Payout'].astype(str)
#Aatmanirbhar -3
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Penalty')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Deep Hunters - Hisaab Tab
sheet= client.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet('Penalty')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Roaring Lions - Hisaab Tab
sheet= client.open('Roaring Lions - Hisaab Tab')
ws= sheet.worksheet('Penalty')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Black Panthers - Hisaab Tab
sheet= client.open('Black Panthers - Hisaab Tab')
ws= sheet.worksheet('Penalty')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Silent Killers - Hisaab Tab
sheet= client.open('Silent Killers - Hisaab Tab')
ws= sheet.worksheet('Penalty')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Terrific Tigers - Hisaab Tab
sheet= client.open('Terrific Tigers - Hisaab Tab')
ws= sheet.worksheet('Penalty')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Attrition Team - Hisaab Tab
sheet= client.open('Attrition Team - Hisaab Tab')
ws= sheet.worksheet('Penalty')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
print("Penalty updated successfully")

In [7]:
scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Adjustments')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,7,3]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Date']= df['Date'].str.replace('/', '-')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce',format='%d-%m-%Y')
df_5week = df[(df['Date'] >= pd.to_datetime(previous_monday_week)) & (df['Date'] < pd.to_datetime(previous_monday))]
df_5week['Date']=df_5week['Date'].astype(str)
df_5week
# Aatmanirbhar -3
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Adjustments')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

,Date,ETM ID,Amount,Remark,Status,Type
6634,2022-04-18,ETM00836,500,Need to adjust Rs 500 as it was Wrong RTO fine...,TRUE,RTO fine reversal
6636,2022-04-18,ETM08538,69,Need to adjust Rs 69 as it was non trip balance,TRUE,Other additon
6637,2022-04-18,ETM04307,1180,Need to deduct Rs 1180 as it was paid to drive...,TRUE,Deposit adjustments
6638,2022-04-18,ETM11543,500,Need to adjust Rs 500 as it was paid by driver...,TRUE,RTO fine reversal
6639,2022-04-18,ETM04307,75,Need to adjust Rs 75 as it was Fast tag not us...,TRUE,Other additon
...,...,...,...,...,...,...
10208,2022-05-21,ETM06666,531,Need to add 3% of revenue life time for week 1...,TRUE,Life time incentive
10209,2022-05-21,ETM07674,874,Need to add 3% of revenue life time for week 1...,TRUE,Life time incentive
10210,2022-05-21,ETM06345,674,Need to add 3% of revenue life time for week 1...,TRUE,Life time incentive
10211,2022-05-21,ETM03924,17,Need to add 3% of revenue life time for week 1...,TRUE,Life time incentive
10213,2022-05-22,ETM15905,1000,Need to add joining Bonus for the period of 0...,TRUE,Joining Bonus

In [8]:
scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('New SMS Data')
data = ws.get_all_values()
headers = data.pop(1)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[2,3,4,26,31,32,0,1]]
#Aatmanirbhar -3
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('New SMS Data')
ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')
print("New sms data updated successfully")

New sms data updated successfully

In [ ]:
ws.batch_clear(['A:B'])

In [9]:
scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Driver Hisaab')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[1,2,3,4,5]]
#Aatmanirbhar -3
sheet= client.open('Aatmanirbhar -3')
ws= sheet.worksheet('Driver Hisaab')
ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')

{'spreadsheetId': '1cC9dKh4tvSHQuL5ncSJgxD79IyeYlVYwSx-mU1Hz3fI',
 'updatedRange': "'Driver Hisaab'!A1:E20724",
 'updatedRows': 20724,
 'updatedColumns': 5,
 'updatedCells': 103620}

In [16]:
#uber

scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
client= gspread.authorize(credentials)
sheet= client.open('Car Master Sheet')
ws= sheet.worksheet('Uber')
data = ws.get_all_values()
headers = data.pop(0)
dfm = pd.DataFrame(data,columns=headers)
df=dfm.iloc[:,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
today = datetime.date.today()
previous_monday = today - datetime.timedelta(days=today.weekday())
previous_monday_week= previous_monday - datetime.timedelta(days=35)
df['Week start Date']= df['Week start Date'].str.replace('-', '/')
df['Week End Date']= df['Week End Date'].str.replace('-', '/')
df[['Week start Date','Week End Date']] = df[['Week start Date','Week End Date']].apply(pd.to_datetime, errors='coerce',format='%d/%m/%Y')
df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
df_5week['Week End Date']=df_5week['Week End Date'].astype(str)

# not to update Uber in 26/05/2022 Aatmanirbhar -3 sameer sir uber tab is not in aatmanirbhar-3
# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
#Deep Hunters - Hisaab Tab
sheet= client.open('Deep Hunters - Hisaab Tab')
ws= sheet.worksheet('Uber')
ws.clear()
ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
# #Roaring Lions - Hisaab Tab
# sheet= client.open('Roaring Lions - Hisaab Tab')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
# #Black Panthers - Hisaab Tab
# sheet= client.open('Black Panthers - Hisaab Tab')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
# #Silent Killers - Hisaab Tab
# sheet= client.open('Silent Killers - Hisaab Tab')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
# #Terrific Tigers - Hisaab Tab
# sheet= client.open('Terrific Tigers - Hisaab Tab')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
# #Attrition Team - Hisaab Tab
# sheet= client.open('Attrition Team - Hisaab Tab')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')
# print("Uber updated successfully")

{'spreadsheetId': '1D1LD-SP8-tf29XytOyrK277z0jeOZd3t0IdagbioHqs',
 'updatedRange': 'Uber!A1:V6097',
 'updatedRows': 6097,
 'updatedColumns': 22,
 'updatedCells': 134134}

In [22]:
today = datetime.date.today()
# previous_monday = today - datetime.timedelta(days=today.weekday())
# print(previous_monday)
previous_monday_week= today - datetime.timedelta(days=42)
print(previous_monday_week)
print(today)

2022-04-07
2022-05-19

In [2]:
#importing libraries

import pandas as pd
import datetime
from datetime import date, timedelta
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import warnings
warnings.filterwarnings("ignore")

C:\Users\sagar\anaconda3\lib\site-packages\gspread\__init__.py

In [33]:
# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Car Master Sheet')
# ws= sheet.worksheet('New SMS Data')
# data = ws.get_all_values()
# headers = data.pop(1)
# dfm = pd.DataFrame(data,columns=headers)
# # df=dfm.loc[:,['Contact No','Name','ETM','Total Earnings(Sum(Q:S)-T)','Pending Joining Fee','Total Outstanding as of 16 May']]
# df=dfm.iloc[:,[2,3,4,26,31,32]]#old indexes
# df=dfm.iloc[:,[2,3,4,23,28,29]]#new indexes

# sheet= client.open('Aatmanirbhar -3')
# ws= sheet.worksheet('New SMS Data')
# ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')
# print("New sms data updated succesfully")

In [36]:
# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Car Master Sheet')
# ws= sheet.worksheet('Uber')
# data = ws.get_all_values()
# headers = data.pop(0)
# dfm = pd.DataFrame(data,columns=headers)
# df=dfm.iloc[:,[0,1,5,4,6,8,12,13,14,15,16,21,23,24,11,19,9,10,26,27,28,29]]
# today = datetime.date.today()
# previous_monday = today - datetime.timedelta(days=today.weekday())
# previous_monday_week= previous_monday - datetime.timedelta(days=35)
# df['Week start Date']= df['Week start Date'].str.replace('/', '-')
# df['Week End Date']= df['Week End Date'].str.replace('/', '-')
# df[['Week start Date','Week End Date']] = df[['Week start Date','Week End Date']].apply(pd.to_datetime, errors='coerce',format='%d-%m-%Y')
# df_5week = df[(df['Week start Date'] >= pd.to_datetime(previous_monday_week)) & (df['Week start Date'] < pd.to_datetime(previous_monday))]
# df_5week['Week start Date']=df_5week['Week start Date'].astype(str)
# df_5week['Week End Date']=df_5week['Week End Date'].astype(str)
# #Attrition Team - Hisaab Tab
# sheet= client.open('Attrition Team - Hisaab Tab')
# ws= sheet.worksheet('Uber')
# ws.update([df_5week.columns.values.tolist()] + df_5week.values.tolist(),value_input_option='USER_ENTERED')

{'spreadsheetId': '1jxkUUu01Q_x670bLevdiuXgK_SNHvdKfDmJSndTmeVY',
 'updatedRange': 'Uber!A1:V6162',
 'updatedRows': 6162,
 'updatedColumns': 22,
 'updatedCells': 135564}

In [22]:
print("qwerty")
print("\n")
print("qwerty")

qwerty


qwerty

In [19]:
# scope= ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
# credentials= ServiceAccountCredentials.from_json_keyfile_name('client_secret.json', scope) 
# client= gspread.authorize(credentials)
# sheet= client.open('Car Master Sheet')
# ws= sheet.worksheet('New SMS Data')
# data = ws.get_all_values()
# headers = data.pop(1)
# dfm = pd.DataFrame(data,columns=headers)
# df=dfm.iloc[0:-1,[2,3,4,26,31,32]]
# ws= sheet.worksheet('New SMS Data')
# ws.update([df.columns.values.tolist()] + df.values.tolist(),value_input_option='USER_ENTERED')
# print("New sms data updated succesfully")

New sms data updated succesfully

{'spreadsheetId': '1oQKfbWGh_Du55RspSLMgDz22apHcSM5CRArzHSqtELA',
 'updatedRange': 'Uber!A1:V6162',
 'updatedRows': 6162,
 'updatedColumns': 22,
 'updatedCells': 135564}

Amount paid updated successfully
New sms data updated successfully
Uber updated successfully
Vistor responses updated successfully
Dm updated succesfully


All sheets updated successfully

NameError: name 'ServiceAccountCredentials' is not defined

Driver hisaab updated successfully